
[Container]
	#Defineds drinks will be influenced by purity
	#Format: ["examplemod:example_item_1", "examplemod:example_item_2"]
	Containers = ["minecolonies:large_water_bottle", "morebuckets:wooden_bucket", "morebuckets:stone_bucket", "morebuckets:ceramic_bucket", "collectorsreap:pomegranate_black_tea", "collectorsreap:lime_green_tea", "create:builders_tea"]

