
["通用配置"]
	#简易化材料寻找AI：工人在架子上找原材料时，将直接在对应的小屋方块建筑进行。
	easy_pick_material_ai = true
	#非殖民地食物惩罚倍率：市民食用非殖民地食物带来的饱食度惩罚倍率，原版为缩减倍率至：0.25
	#Range: 0.0 ~ 2.147483647E9
	not_colony_food_penalty_multiplier = 0.75
	#受击提示：是否允许非警卫市民受到攻击后发出警报。
	allow_hurt_alert = true
	#允许默认开启配方模式：开启后将不需要在大学研究也可以直接解锁小屋配方模式的切换。
	allow_recipe_mode_as_default = true
	#默认使用库存模式：开启后将默认使用库存模式作为小屋的合成模式，对于已经放置的小屋不奏效。
	use_max_stock_as_default = true

["建筑工人配置"]
	#简易化建筑工人AI：建筑工人将固定在施工现场的工作方块附近建筑。
	easy_builder_ai = true
	#建筑工人间隔模式：可选择 fixed 或 magnification，对应下列的建筑工间隔修正模式，选择其他的则视为无效。
	builder_delay_mode = "off"
	#建筑工人间隔倍率：扩大或缩小建筑工人建筑、破坏的间隔倍率，只有建筑工人固定间隔设置为 magnification 时，该选项生效。
	#Range: 0.0 ~ 2.147483647E9
	builder_delay_magnification = 1.0
	#建筑工人间隔：建筑工人间隔的固定值，只有建筑工人固定间隔设置为 fixed 时，该选项生效。
	#Range: > 0
	builder_fixed_delay = 15

["合成工人配置"]
	#允许石匠使用切石机配方：决定是否允许石匠使用切石机配方，当设置为 false 后不会影响已经教授的配方，但会导致所有配方被禁用。
	allow_stone_cutting = true

["复活配置"]
	#是否允许玩家手动复活市民：如果允许，玩家将可以使用指定物品复活市民，成功率取决于总幸福度和墓地等级。
	allow_resurrect = true
	#复活市民所需物品：指定玩家复活市民所需的物品。
	resurrect_item = "minecraft:totem_of_undying"
	#复活市民几率乘数：会在原有的复活概率基础上额外乘以一个系数。
	#Range: 0.0 ~ 2.147483647E9
	resurrect_chance_multiplier = 1.0

["市民思维读取器设置"]
	#是否允许玩家读取市民行动：如果允许，玩家将可以手持特定物品右键市民读取市民当前行动。
	allow_read_mind = true
	#读取行动所需物品：指定玩家读取市民行动所需的物品，不会消耗。
	read_mind_item = "minecraft:compass"

["彩蛋设置"]
	#是否允许清明节彩蛋：如果允许，在坟墓前烧纸可以让死亡的市民安息，市民们将不会再第二天为其哀悼，但是同样该市民将无法复活。
	allow_burn_paper = true

["测试版功能设置"]
	#是否允许多组合成：是否允许合成类工人一次性合成多个物品，允许则会像玩家一样一次性填满一组合成。
	allow_craft_multi = false
	#多组合成上限：建筑工人一次性多组合成的次数上限。
	#Range: > 64
	multi_craft_max = 64
	#多组合成截距：单次合成公式为 y = kx+b 形式，x 为工人的次要属性属性。此配置决定b。
	#Range: > 1
	multi_craft_intercept = 4
	#多组合成斜率：单次合成公式为 y = kx+b 形式，x 为工人的技巧属性。此配置决定k。
	#Range: 0.0 ~ 2.147483647E9
	multi_craft_slope = 0.75

