#Enable a multiblock brick furnace with unique recipes?
"Enable Kiln" = false
#Enable smeting raw ore blocks in the kiln
"Kiln Ore Smelting" = false
#Enable obtaining knapped rocks by hitting two normal rocks
"Rock Knapping" = true
#Enable obtaining Rock by hitting stone with item tagged as rock_obtainers (Only flint by default). Note that disabling this setting does not bring back vanilla stone tool recipes
"Rock Obtaining" = true

