#This modifies the distance a special multiblock renderer is visible from Default is 2.5
#Range: 0.0 ~ 1.7976931348623157E308
multiblockSpecialRenderDistanceModifier = 2.5
#This controls if the animations and special client rendering applies to the Gravity Separator
gravity_separator_renderer = true
#This controls if the animations and special client rendering applies to the Core Drill
core_dill_renderer = true
#This controls if the animations and special client rendering applies to the Pelletizer
pelletizer_renderer = true
#This controls if the animations and special client rendering applies to the Chemical Reactor
chemical_reactor_renderer = true
#This controls if the animations and special client rendering applies to the Rotary Kiln
rotary_kiln_renderer = true
#This controls if the animations and special client rendering applies to the Centrifuge
centrifuge_renderer = true
#This controls if the animations and special client rendering applies to the Ballmill
ballmill_renderer = true
#This controls if the animations and special client rendering applies to the Steam Turbine
steam_turbine_renderer = true
#This controls if the animations and special client rendering applies to the Alternator
alternator_renderer = true

