
#minecolonies.config.gameplay.comment
[gameplay]
	#minecolonies.config.generatesupplyloot.comment minecolonies.config.default.boolean
	generatesupplyloot = true

#minecolonies.config.requestsystem.comment
[requestsystem]
	#minecolonies.config.enabledebuglogging.comment minecolonies.config.default.boolean
	enabledebuglogging = false

