# Reputation tooltip will be shown when looking at a Villager.
# Default: true.
show_villager_reputation_tooltip = true
# Villager reputation tooltip requires item tagged as '#thief:villager_gifts' in hand.
# Default: true.
villager_reputation_tooltip_requires_gift = true

